services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./db:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: mcpcurso


  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8080