apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-curso-app
  namespace: mcp-curso-dev
  labels:
    app: mcp-curso-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcp-curso-app
  template:
    metadata:
      labels:
        app: mcp-curso-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"