apiVersion: v1
kind: Service
metadata:
  name: mcp-curso-service
  namespace: mcp-curso-dev
  labels:
    app: mcp-curso-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: mcp-curso-app